# Generated by Django 5.0.2 on 2024-03-02 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('user_name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('ac_uid', models.CharField(max_length=36)),
                ('pw', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('b_uid', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('book_name', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('volume', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('accession_no', models.IntegerField(primary_key=True, serialize=False)),
                ('sc_uid', models.CharField(max_length=20)),
                ('b_uid', models.CharField(max_length=36)),
                ('issue_date', models.DateField()),
                ('expiry_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('sc_uid', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('roll_no', models.CharField(max_length=15)),
            ],
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
