# Generated by Django 5.0.2 on 2024-03-02 14:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_admin_book_cart_students_delete_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='issue_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
